[workspace]
members = ["cargo:tools/gte/frontend", "cargo:tools/gtrom", "cargo:tools/gtgo", "cargo:tools/gtld"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.2"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Which actions to run on pull requests
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = false
# A GitHub repo to push Homebrew formulas to
tap = "dwbrite/tap"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Whether to run otherwise-parallelizable tasks on the same machine
merge-tasks = true

# System dependencies for Linux builds
[dist.dependencies.apt]
libasound2-dev = "*"
libjack-jackd2-dev = "*"
libudev-dev = "*"
