[package]
name = "gametank-libretro"
version = "0.1.3"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gte-core = { path = "../core" }

[dependencies.libretro-rs]
git = "https://github.com/libretro-rs/libretro-rs"
rev = "c7f414d19d837921b8762656e53e7f1b8f892179"

